language: ruby

env:
  - DB=mysql
  
services:
    -mysql2

script:
  - bundle exec rake    
    
before_script:
  - cp config/database.travis.yml config/database.yml
  - mysql -e "create database IF NOT EXISTS c9;"
  - mysql -e "create database IF NOT EXISTS test;" 
  - mysql -e "create database IF NOT EXISTS production;"